#!/usr/bin/env ruby
message_file = ARGV[0]
message = File.read(message_file)

$regex = /Re: #(\d+)/

if !$regex.match(message)
  puts "[POLICY] Your commit message needs to reference an Assembla ticket (Re: #1234)"
  exit 1
end
